import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Currency = {
  code: string;
  name: string;
  symbol: string;
};

export const currencies: Currency[] = [
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
];

export type Language = 'en' | 'sw';

type SettingsContextType = {
  currency: Currency;
  language: Language;
  setCurrency: (currency: Currency) => void;
  setLanguage: (language: Language) => void;
  formatCurrency: (value: number) => string;
  t: (key: string) => string;
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

const defaultCurrency = currencies.find((c) => c.code === 'KES')!;

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_home: 'Home',
    nav_transactions: 'Transactions',
    nav_report: 'Report',
    nav_plan: 'Plan',
    nav_settings: 'Settings',
    balance: 'Current Balance',
    income: 'Income',
    expense: 'Expenses',
    transactions: 'Transactions',
    see_all: 'See All',
    no_transactions: 'No transactions yet',
    start_tracking: 'Start tracking your spending',
    add_transaction: 'Tap the + button to add one',
    no_transactions_found: 'No transactions found',
    try_adjusting: 'Try adjusting your filters',
    report: 'Report',
    finance: 'Finance',
    monthly_spending: 'Monthly spending',
    spend_breakdown: 'Spend breakdown',
    by_category: 'By category',
    total: 'Total',
    of_total: 'of total expenses',
    vs_last_month: '% vs last month',
    my_plan: 'My Plan',
    goals: 'Goals',
    budgets: 'Budgets',
    view_all: 'View All',
    goal: 'Goal',
    budget: 'Budget',
    settings: 'Settings',
    profile_info: 'Profile Information',
    profile_desc: 'Name, email',
    security: 'Security',
    security_desc: 'Password, biometrics',
    notification: 'Notification',
    notification_desc: 'Push, email alerts',
    currency_language: 'Currency & Language',
    appearance: 'Appearance',
    appearance_desc: 'Theme',
    data_privacy: 'Data & Privacy',
    help_support: 'Help & Support',
    about: 'About',
    about_intro: 'Finances Tracker helps you understand and manage your everyday money in one place.',
    about_track_title: 'Track your money',
    about_track_desc: 'Record income and expenses, then review your transaction history whenever you need it.',
    about_plan_title: 'Plan ahead',
    about_plan_desc: 'Create savings goals and spending budgets, and follow your progress over time.',
    about_insights_title: 'See the bigger picture',
    about_insights_desc: 'Use your dashboard and reports to understand your balance, spending, and financial habits.',
    account: 'Account',
    preferences: 'Preferences',
    push_notifications: 'Push notifications',
    done: 'Done',
    profile_updated: 'Profile updated successfully',
    password_updated: 'Password updated successfully',
    log_out: 'Log Out',
    profile: 'Profile',
    update_profile: 'Update your name and email address.',
    full_name: 'Full Name',
    email: 'Email Address',
    save_changes: 'Save Changes',
    password: 'Password',
    change_password: 'Change your account password.',
    current_password: 'Current Password',
    new_password: 'New Password',
    new_password_placeholder: 'Must be at least 6 characters',
    confirm_password: 'Confirm New Password',
    update_password: 'Update Password',
    add_expense: 'Add Expense',
    add_income: 'Add Income',
    transfer_money: 'Transfer Money',
    create_budget: 'Create Budget',
    create_goal: 'Create Goal',
    track_transaction: 'Track your income or expense',
    saving: 'Saving...',
    save_transaction: 'Save Transaction',
    enter_valid_amount: 'Please enter a valid amount.',
    failed_to_save: 'Failed to save. Please try again.',
    add_new_transaction: 'Add Transaction',
    edit_transaction: 'Edit Transaction',
    update_transaction: 'Update your transaction details',
    save: 'Save Changes',
    edit: 'Edit',
    edit_name_placeholder: 'Enter new name',
    close: 'Close',
    delete: 'Delete',
    delete_confirm: 'Delete Transaction?',
    delete_warning: 'This will permanently remove the transaction.',
    edit_transaction_confirm: 'Are you sure you want to edit this transaction?',
    continue: 'Continue',
    cancel: 'Cancel',
    description: 'Description',
    description_placeholder: 'What was this for? (optional)',
    amount: 'Amount',
    type: 'Type',
    category: 'Category',
    expense_purpose: 'Describe what the expense was for',
    current: 'Current',
    overview: 'Your finances in one polished view.',
    more_than_last_month: 'more than last month',
    dashboard: 'Dashboard',
    home: 'Home',
    your_money: 'Your Money',
    details: 'Details',
    your_insight: 'Your insight is ready',
    monthly_overview: 'Your monthly overview',
    view: 'View',
    accounts: 'Accounts',
    recent_items: 'Recent items',
    total_income: 'Total Income',
    total_expense: 'Total Expense',
    bank_account: 'Bank account',
    credit_card: 'Credit card',
    no_goals: 'No goals yet. Tap + to create your first goal.',
    no_budgets: 'No budgets yet. Use the + menu to create one.',
    completed_goals: 'Completed Goals',
    completed_budgets: 'Completed Budgets',
    active: 'Active',
    completed: 'Completed',
    no_completed_goals: 'No completed goals yet.',
    no_completed_budgets: 'No completed budgets yet.',
    goal_completed: 'Goal completed!',
    budget_completed: 'Budget completed!',
    add_money: 'Add Money',
    add_spending: 'Add Spending',
    add_money_to_goal: 'Add funds to your goal.',
    add_spending_to_budget: 'Record spending against this budget.',
    goal_name: 'Goal name',
    target: 'Target',
    target_amount: 'Target amount (KSh)',
    budget_name: 'Budget name',
    budget_limit: 'Budget limit (KSh)',
    create_goal_btn: 'Create goal',
    create_budget_btn: 'Create budget',
    new_entry: 'New entry',
    purpose: 'Purpose',
    no_expense_data: 'No expense data yet. Add transactions to see your report.',
    of_total_expenses: 'of total expenses',
    currency: 'Currency',
    language: 'Language',
    date: 'Date',
    of: 'of',
    remaining: 'remaining',
    set_savings_target: 'Set a savings target you can track.',
    goal_name_placeholder: 'e.g. Emergency fund',
    set_spending_limit: 'Set a spending limit for a category or purpose.',
    budget_name_placeholder: 'e.g. Groceries',
    english: 'English',
    swahili: 'Swahili',
    notifications: 'Notifications',
    keep_up: 'Keep up with your money.',
    monthly_report: 'Monthly report is ready',
    monthly_report_desc: 'Review your spending for this month.',
    budget_reminder: 'Budget reminder',
    budget_reminder_desc: 'Set a goal in My Plan to start tracking progress.',
    choose_month: 'Choose month',
    july: 'July 2026',
    august: 'August 2026',
    september: 'September 2026',
    october: 'October 2026',
    august_2026: 'August 2026',
    transfer_recorded: 'Transfer recorded successfully.',
    move_money: 'Move money between your tracked accounts.',
    from: 'From',
    to: 'To',
    amount_label: 'Amount (KSh)',
    transfer: 'Transfer money',
    create_account: 'Create Account',
    start_organizing: 'Start organizing your finances beautifully',
    already_have_account: 'Already have an account?',
    sign_in: 'Sign in',
    sign_up: 'Sign up',
    sign_in_to_continue: 'Sign in to continue to your finances',
    dont_have_account: "Don't have an account?",
    welcome_back: 'Welcome back',
    full_name_label: 'Full Name',
    email_label: 'Email Address',
    password_label: 'Password',
    confirm_password_label: 'Confirm Password',
    creating_account: 'Creating Account...',
    signing_in: 'Signing In...',
    password_min: 'Password must be at least 6 characters',
    passwords_dont_match: 'Passwords do not match',
    please_enter_name: 'Please enter your full name',
    please_enter_email: 'Please enter your email address',
    please_enter_both: 'Please enter both email and password',
    sign_in_failed: 'Failed to sign in. Please try again.',
    sign_up_failed: 'Failed to create account. Please try again.',
    check_email: 'Check your email to confirm your account, then sign in.',
    no_expense_data_yet: 'No expense data yet. Add transactions to see your report.',
  },
  sw: {
    nav_home: 'Mwanzo',
    nav_transactions: 'Miamala',
    nav_report: 'Ripoti',
    nav_plan: 'Mpango',
    nav_settings: 'Vigoza',
    balance: 'Salio Juu',
    income: 'Mapato',
    expense: 'Gharama',
    transactions: 'Miamala',
    see_all: 'Tazama Yote',
    no_transactions: 'Hakuna miamala bado',
    start_tracking: 'Anza kufuatilia matumizio yako',
    add_transaction: 'Bonyeza kipengele cha + ili kuongeza moja',
    no_transactions_found: 'Hakuna miamala imekutwa',
    try_adjusting: 'Jaribu kubadilisha viwimbio',
    report: 'Ripoti',
    finance: 'Fedha',
    monthly_spending: 'Matumizi ya kuhoro',
    spend_breakdown: 'Gawanyiko la matumizi',
    by_category: 'Kwa jinsi',
    total: 'Jumla',
    of_total: 'ya jumla ya matumizi',
    vs_last_month: '% dhidi ya mwezi uliopita',
    my_plan: 'Mpango Wangu',
    goals: 'Mazingira',
    budgets: 'Bajeti',
    view_all: 'Tazama Yote',
    goal: 'Malengo',
    budget: 'Bajeti',
    settings: 'Vigoza',
    profile_info: 'Taarifa za Profaili',
    profile_desc: 'Jina, barua pepe',
    security: 'Usalama',
    security_desc: 'Neno la siri, vidokezo',
    notification: 'Arifa',
    notification_desc: 'Arifa za barua pepe',
    currency_language: 'Sarafu na Lugha',
    appearance: 'Onekana',
    appearance_desc: 'Mandhari',
    data_privacy: 'Data na Faragha',
    help_support: 'Msaada na Usaidie',
    about: 'Kuhusu',
    about_intro: 'Finances Tracker hukusaidia kuelewa na kusimamia fedha zako za kila siku mahali pamoja.',
    about_track_title: 'Fuatilia fedha zako',
    about_track_desc: 'Rekodi mapato na matumizi, kisha angalia historia ya miamala yako wakati wowote.',
    about_plan_title: 'Panga mapema',
    about_plan_desc: 'Unda malengo ya akiba na bajeti za matumizi, na fuatilia maendeleo yako kadri muda unavyokwenda.',
    about_insights_title: 'Ona picha kubwa',
    about_insights_desc: 'Tumia dashibodi na ripoti zako kuelewa salio, matumizi, na tabia zako za kifedha.',
    account: 'Akaunti',
    preferences: 'Mapendeleo',
    push_notifications: 'Arifa za barua pepe',
    done: 'Imekamilika',
    profile_updated: 'Profaili imesasishwa',
    password_updated: 'Neno la siri limebadilishwa',
    log_out: 'Toa',
    profile: 'Profaili',
    update_profile: 'Sasisha jina na barua pepe yako.',
    full_name: 'Jina kamili',
    email: 'Barua pepe',
    save_changes: 'Hifadhi mabadiliko',
    password: 'Neno la siri',
    change_password: 'Badilisha neno la siri la akaunti yako.',
    current_password: 'Neno la sasa',
    new_password: 'Neno jipya',
    new_password_placeholder: 'Lazima liwe angalau miji 6',
    confirm_password: 'Thibitisha neno jipya',
    update_password: 'Sasisha neno la siri',
    add_expense: 'Ongeza Gharama',
    add_income: 'Ongeza Mapato',
    transfer_money: 'Piga Pesa',
    create_budget: 'Tengeneza Bajeti',
    create_goal: 'Tengeneza Malengo',
    track_transaction: 'Fuata mapato au gharama yako',
     saving: 'Kuhifadhi...',
    save_transaction: 'Hifadhi Muamala',
    enter_valid_amount: 'Tafadhari weka kiasi sahihi.',
    failed_to_save: 'Haijulikani kuhifadhi. Tafadhari jaribu tena.',
    add_new_transaction: 'Ongeza Muamala',
    edit_transaction: 'Hariri Muamala',
    update_transaction: 'Sasisha maelezo ya muamala',
    save: 'Hifadhi',
    edit: 'Hariri',
    edit_name_placeholder: 'Ingiza jina mpya',
    close: 'Funga',
    delete: 'Futa',
    delete_confirm: 'Futa Muamala?',
    delete_warning: 'Hii itafuta kwa muda kwa dhati muamala huu.',
    edit_transaction_confirm: 'Una uhakika unataka kuhariri muamala huu?',
    continue: 'Endelea',
    cancel: 'Ghairi',
    description: 'Maelezo',
    description_placeholder: 'Je, hii ilikuwa kwa nini? (si lazima)',
    amount: 'Kiasi',
    type: 'Aina',
    category: 'Jinsi',
    expense_purpose: 'Eleza kwa nini gharama hii ilitokonitwa',
    current: 'Sasa',
    overview: 'Fedha zako katika muonekano mzuri.',
    more_than_last_month: 'zaidi ya mwezi uliopita',
    dashboard: 'Bango',
    home: 'Mwanzo',
    your_money: 'Pesa zako',
    details: 'Maelezo',
    your_insight: 'Maoni yako yamepita',
    monthly_overview: 'Muhtaso wa kuhoro wako',
    view: 'Tazama',
    accounts: 'Akaunti',
    recent_items: 'Vitu vya karibu',
    total_income: 'Jumla ya Mapato',
    total_expense: 'Jumla ya Gharama',
    bank_account: 'Akaunti ya benki',
    credit_card: 'Kadi ya mkopo',
    no_goals: 'Hakuna malengo bado. Bonyeza + ili kutengeneza malengo yako ya kwanza.',
    no_budgets: 'Hakuna bajeti bado. Tumia menyu ya + ili kutengeneza moja.',
    completed_goals: 'Malengo Yamekamilika',
    completed_budgets: 'Bajeti Zimekamilika',
    active: 'Inaendelea',
    completed: 'Imekamilika',
    no_completed_goals: 'Bado hakuna malengo yaliyokamilika.',
    no_completed_budgets: 'Bado hakuna bajeti zilizokamilika.',
    goal_completed: 'Malengo yamekamilika!',
    budget_completed: 'Bajeti imekamilika!',
    add_money: 'Ongeza Pesa',
    add_spending: 'Ongeza Gharama',
    add_money_to_goal: 'Ongeza fedha kwenye malengo yako.',
    add_spending_to_budget: 'Rekodia gharama dhidi ya bajeti hii.',
    goal_name: 'Jina la malengo',
    target: 'Lengo',
    target_amount: 'Kiasi la kipekee (KSh)',
    budget_name: 'Jina la bajeti',
    budget_limit: 'Hatiri ya bajeti (KSh)',
    create_goal_btn: 'Tengeneza malengo',
    create_budget_btn: 'Tengeneza bajeti',
    new_entry: 'Ingizo jipya',
    purpose: 'Kwa nini',
    no_expense_data: 'Hakuna data ya gharama bado. Ongeza miamala ili kuona ripoti yako.',
    of_total_expenses: 'ya jumla ya matumizi',
     currency: 'Sarafu',
    language: 'Lugha',
    date: 'Tarehe',
    of: 'ya',
    remaining: 'y baki',
    set_savings_target: 'Weka lengizo za akiba unayoweza kufuatilia.',
    goal_name_placeholder: 'k.m. Pesa za dharura',
    set_spending_limit: 'Weka kipimo cha matumizi kwa jinsi au kwa nini.',
    budget_name_placeholder: 'k.m. Mlo',
    english: 'Kiingereza',
    swahili: 'Kiswahili',
    notifications: 'Arifa',
    keep_up: 'Endelea na pesa zako.',
    monthly_report: 'Ripoti ya kuhoro imetayari',
    monthly_report_desc: 'Chunguza matumizi yako kwa mwezi huu.',
    budget_reminder: 'Ukumbusho wa bajeti',
    budget_reminder_desc: 'weka malengo katika Mpango Wangu ili kuanza kufuatilia maendeleo.',
    choose_month: 'Chagua mwezi',
    july: 'Julai 2026',
    august: 'Agosti 2026',
    september: 'Septemba 2026',
    october: 'Oktoba 2026',
    august_2026: 'Agosti 2026',
    transfer_recorded: 'Muamala wa pesa uliohifadhiwa.',
    move_money: 'Sogeza pesa kati ya akaunti zako.',
    from: 'Kutoka',
    to: 'Kwenda',
    amount_label: 'Kiasi (KSh)',
    transfer: 'Piga pesa',
    create_account: 'Tengeneaza Akaunti',
    start_organizing: 'Anza ku organizing fedha zako mzuri',
    already_have_account: 'Tayari una akaunti?',
    sign_in: 'Ingia',
    sign_up: 'Jisajili',
    sign_in_to_continue: 'Ingia ili kuendelea na fedha zako',
    dont_have_account: "Huna akaunti?",
    welcome_back: 'Karibu tena',
    full_name_label: 'Jina kamili',
    email_label: 'Barua pepe',
    password_label: 'Neno la siri',
    confirm_password_label: 'Thibitisha neno la siri',
    creating_account: 'Inatengeneza akaunti...',
    signing_in: 'Inaingia...',
    password_min: 'Neno la siri lazima liwe angalau miji 6',
    passwords_dont_match: 'Maneno ya siri hujalingana',
    please_enter_name: 'Tafadhali ingiza jina kamili',
    please_enter_email: 'Tafadhali ingiza barua pepe',
    please_enter_both: 'Tafadhali ingiza barua pepe na neno la siri',
    sign_in_failed: 'Imeshindwa kuingia. Tafadhali ujaribu tena.',
    sign_up_failed: 'Imeshindwa kutengeneza akaunti. Tafadhali ujaribu tena.',
    check_email: 'Angalia barua pepe yako ili kuthibitisha akaunti yako, kisha ingia.',
    no_expense_data_yet: 'Hakuna data ya gharama bado. Ongeza miamala ili kuona ripoti yako.',
  },
};

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [currency, setCurrencyState] = useState<Currency>(() => {
    const saved = localStorage.getItem('currency');
    return currencies.find((c) => c.code === saved) || defaultCurrency;
  });
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return saved === 'sw' || saved === 'en' ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('currency', currency.code);
  }, [currency]);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setCurrency = (c: Currency) => setCurrencyState(c);
  const setLanguage = (l: Language) => setLanguageState(l);

  const formatCurrency = (value: number) =>
    `${currency.symbol} ${value.toLocaleString(language === 'sw' ? 'en-KE' : undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  const t = (key: string) => {
    return translations[language][key] ?? key;
  };

  return (
    <SettingsContext.Provider value={{ currency, language, setCurrency, setLanguage, formatCurrency, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
}
